---
  - name: "make sure to use project {{ TARGET_NAMESPACE }}"
    command: "oc project {{ TARGET_NAMESPACE }}"
    register: project_exists

  - name: check if required Templates exist
    command: "oc get template --namespace {{ THOTH_INFRA_NAMESPACE  }} {{ item }}"
    with_items:
      - "thoth-core-secret"
      - "thoth-core-configmap"
    changed_when: false

  - name: "creating Secret"
    shell: oc process --namespace="{{ THOTH_INFRA_NAMESPACE }}" thoth-core-secret \
        -p THOTH_APP_SECRET_KEY="{{ THOTH_APP_SECRET_KEY }}" \
        -p THOTH_SECRET="{{ THOTH_SECRET }}" \
        -p THOTH_CEPH_KEY_ID="{{ THOTH_CEPH_KEY_ID }}" \
        -p THOTH_CEPH_SECRET_KEY="{{ THOTH_CEPH_SECRET_KEY }}" \
        -p SENTRY_DSN="{{ SENTRY_DSN }}" \
        -p MANAGEMENT_API_TOKEN="{{ THOTH_SECRET }}" | oc apply -f -

  - name: "creating ConfigMap"
    shell: oc process --namespace="{{ THOTH_INFRA_NAMESPACE  }}" thoth-core-configmap \
        -p AMUN_API_URL="{{ AMUN_API_URL }}" \
        -p THOTH_DEPLOYMENT_NAME="{{ THOTH_DEPLOYMENT_NAME }}" \
        -p THOTH_FRONTEND_NAMESPACE="{{ THOTH_FRONTEND_NAMESPACE }}" \
        -p THOTH_MIDDLETIER_NAMESPACE="{{ THOTH_MIDDLETIER_NAMESPACE }}" \
        -p THOTH_BACKEND_NAMESPACE="{{ THOTH_BACKEND_NAMESPACE }}" \
        -p THOTH_INFRA_NAMESPACE="{{ THOTH_INFRA_NAMESPACE }}" \
        -p THOTH_S3_ENDPOINT_URL="{{ THOTH_S3_ENDPOINT_URL  }}" \
        -p THOTH_CEPH_BUCKET="{{ THOTH_CEPH_BUCKET }}" \
        -p PROMETHEUS_PUSHGATEWAY_HOST="{{ PROMETHEUS_PUSHGATEWAY_HOST }}" \
        -p PROMETHEUS_PUSHGATEWAY_PORT="{{ PROMETHEUS_PUSHGATEWAY_PORT }}" | oc apply -f -
